name: Trojan-Go Build
on:
  watch:
    types: [started]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        go-version: [1.16.x]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build Trojan-Go
        run: make

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Trojan-Go-${{ matrix.platform }}
          path: build/
